In [1]:
import numpy as np
from tensorflow.keras.utils import to_categorical
import json
import _pickle as cPickle
from numpy import load
from sklearn.utils import shuffle
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import Dense, Dropout, Flatten, MaxPooling1D, BatchNormalization, GlobalAveragePooling1D,Activation
from tensorflow.keras.models import Sequential

from tensorflow.keras import backend as K
import random
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, LearningRateScheduler
import numpy as np
import tensorflow_addons as tfa
import tensorflow 
from sklearn.utils import shuffle
import tensorflow as tf
from tensorflow_addons.optimizers import extend_with_decoupled_weight_decay
from tensorflow.keras.models import Model
from tensorflow.python.ops.numpy_ops import np_config
from sklearn.metrics import accuracy_score
np_config.enable_numpy_behavior()

In [2]:
import json
import numpy as np
from tensorflow.keras.utils import to_categorical
import json
import pickle
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


def Exchange_classes(c1,c2,y):
  for i in range(len(y)):
    if y[i]==c1:
      y[i]=c2
      
    elif y[i]==c2:
      y[i]=c1


def balance_dataset(X,y):
  Classes=int(np.max(y))+1
  k=len(y)//Classes-1
  X_=list(np.zeros(k*Classes))
  y_=list(np.zeros(k*Classes))
  
  
  for j in range(Classes):
    for i in range(k):
      y_[i*Classes+j]=j
      Index=list(y).index(j)
      X_[i*Classes+j]=X[Index]
      y[Index]=1000
  
  y=np.array(y_)
  X=np.array(X_)
  return X,y
  
def Filter_close_set(Split_Number,data):
  closed_set=data[Split_Number]["closed"]
  open_set=data[Split_Number]["open"]
  X_5=[]
  X_open=[]
  y_5=[]
  y_open=[]
  for i in range(len(y)):
    if y[i] in closed_set:
      y_5.append(closed_set.index(y[i]))
      X_5.append(X[i])
    else:
      y_open.append(40)
      X_open.append(X[i])
      
  return X_5,X_open,y_5,y_open
  
  
f = open('../input/sydney-data/IOT_data_file.json')
data = json.load(f)
print(data["1"])  


dataset_dir = "../input/sydney-data/dataset/"
X_train = np.load(dataset_dir+'X_train.npy')
print(X_train.shape)
y_train = np.load(dataset_dir+'y_train.npy')
#print(list(y_train).count(0),list(y_train).count(1),list(y_train).count(2),list(y_train).count(3),list(y_train).count(4),list(y_train).count(5),list(y_train).count(6),list(y_train).count(7),list(y_train).count(8),list(y_train).count(9))

    # Load testing data
X_test = np.load(dataset_dir+'X_test.npy')
y_test = np.load(dataset_dir+'y_test.npy')


    # Load testing data
X_valid = np.load(dataset_dir+'X_valid.npy')
y_valid = np.load(dataset_dir+'y_valid.npy')

X=np.concatenate((X_train, X_test,X_valid), axis=0)
y=np.concatenate((y_train, y_test,y_valid), axis=0)

  
#X,y=balance_dataset(X,y)

print(X.shape)
print(y.shape)
print(X[:5])



Split_Number="6"
  
  
X_5,X_open,y_5,y_open=Filter_close_set(Split_Number,data)


  
X_train_5, X_valid_5, y_train_5, y_valid_5 = train_test_split(X_5, y_5, test_size=0.3, shuffle=False)
X_valid_5, X_test_5, y_valid_5, y_test_5 = train_test_split(X_valid_5, y_valid_5, test_size=0.4, shuffle=False)

X_train_5,y_train_5=shuffle(X_train_5, y_train_5)
X_valid_5,y_valid_5=shuffle(X_valid_5, y_valid_5)
X_test_5,y_test_5=shuffle(X_test_5, y_test_5)


X_train_5=np.array(X_train_5)
X_valid_5=np.array(X_valid_5)
X_test_5=np.array(X_test_5)
y_train_5=np.array(y_train_5)
y_valid_5=np.array(y_valid_5)
y_test_5=np.array(y_test_5)
X_open=np.array(X_open)
y_open=np.array(y_open)


#print(y_test)
#print("##############")
#print(y_test_5)

print ("Data dimensions:")
print ("X: Training data's shape : ", X_train_5.shape)
print ("X: Validating data's shape : ", X_valid_5.shape)
print ("X: Testing data's shape : ", X_test_5.shape)
print ("X: open data's shape : ", X_open.shape)
    
np.save('X_train_5.npy',X_train_5)
np.save('X_valid_5.npy',X_valid_5)
np.save('X_test_5.npy',X_test_5)
np.save('y_valid_5.npy',y_valid_5)
np.save('y_train_5.npy',y_train_5)
np.save('y_test_5.npy',y_test_5)
np.save('X_open.npy',X_open)
np.save('y_open.npy',y_open)

#print(y_train_5[:50])
#print()
#print(y_valid_5[:50])
#print()
#print(y_test_5[:50])
#print()
#print(y_open[:50])
#print()

{'closed': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], 'open': [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]}
(88044, 475)
(146741, 475)
(146741,)
[[ 1.  1.  1. ...  0.  0.  0.]
 [ 1. -1. -1. ...  0.  0.  0.]
 [ 1.  1.  1. ...  0.  0.  0.]
 [-1. -1. -1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]]
Data dimensions:
X: Training data's shape :  (41962, 475)
X: Validating data's shape :  (10790, 475)
X: Testing data's shape :  (7194, 475)
X: open data's shape :  (86795, 475)


In [3]:
def normalize(X,epsilon=1e-8):
		
    Raws=X.shape[0]
    Columns=X.shape[1]
    for i in range(Raws):
        Tot=0
        for j in X[i]:
            Tot+=j
            mean=Tot/Columns

        Dis=0
        for j in X[i]:
            Dis+=(j-mean)**2
            Var=Dis/Columns

        X[i]=(X[i]-mean)/(np.sqrt(Var)+epsilon)
                                        
    return X

# # Load data for non-defended dataset for CW setting
def LoadDataIot():

    dataset_dir = './'

    # X represents a sequence of traffic directions
    # y represents a sequence of corresponding label (website's label)

    # Load training data
    
    X_train = load(dataset_dir+'X_train_5.npy')
    y_train = load(dataset_dir+'y_train_5.npy')

    
    # Load validation data
    X_valid = load(dataset_dir+'X_valid_5.npy')
    y_valid = load(dataset_dir+'y_valid_5.npy')

    # Load testing data
    X_test = load(dataset_dir+'X_test_5.npy')
    y_test = load(dataset_dir+'y_test_5.npy')

    X_train, y_train = shuffle(X_train, y_train)
    
    print ("Data dimensions:")
    print ("X: Training data's shape : ", X_train.shape)
    print ("y: Training data's shape : ", y_train.shape)
    print ("X: Validation data's shape : ", X_valid.shape)
    print ("y: Validation data's shape : ", y_valid.shape)
    print ("X: Testing data's shape : ", X_test.shape)
    print ("y: Testing data's shape : ", y_test.shape)

    return X_train, y_train, X_valid, y_valid, X_test, y_test


class DFNet:
    @staticmethod
    def build(input_shape, nb_classes=98, trainable=True):

        model = Sequential()

        # Feature Extractor
        model.add(Conv1D(128, kernel_size=7, activation='tanh', input_shape=input_shape, use_bias=False, trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.1, trainable=trainable))

        model.add(Conv1D(128, kernel_size=19, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.3, trainable=trainable))

        model.add(Conv1D(64, kernel_size=13, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.1, trainable=trainable))

        model.add(Conv1D(256, kernel_size=23, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(GlobalAveragePooling1D(trainable=trainable))

        model.add(Dense(180, activation='elu'))
        model.add(BatchNormalization())
        model.add(Dense(150, activation='elu'))
        model.add(BatchNormalization())
        model.add(Dense(nb_classes,name='phenultimate_layer'))
        model.add(Activation('softmax', name='softmax', trainable=trainable))

        return model
        
class DFNet_Dropout:
    @staticmethod
    def build(input_shape, nb_classes=98, trainable=True):

        model = Sequential()

        # Feature Extractor
        model.add(Conv1D(128, kernel_size=7, activation='tanh', input_shape=input_shape, use_bias=False, trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.3, trainable=trainable))

        model.add(Conv1D(128, kernel_size=19, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.5, trainable=trainable))

        model.add(Conv1D(64, kernel_size=13, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.3, trainable=trainable))

        model.add(Conv1D(256, kernel_size=23, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(GlobalAveragePooling1D(trainable=trainable))

        model.add(Dense(180, activation='elu'))
        model.add(BatchNormalization())
        model.add(Dropout(rate=0.5, trainable=trainable))
        model.add(Dense(150, activation='elu'))
        model.add(BatchNormalization())
        model.add(Dense(nb_classes,name='phenultimate_layer'))
        model.add(Activation('softmax', name='softmax', trainable=trainable))

        return model
        

class DFNet_Add_Layer:
    @staticmethod
    def build(input_shape, nb_classes=98, trainable=True):

        model = Sequential()

        # Feature Extractor
        model.add(Conv1D(128, kernel_size=7, activation='tanh', input_shape=input_shape, use_bias=False, trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.3, trainable=trainable))

        model.add(Conv1D(128, kernel_size=19, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.5, trainable=trainable))

        model.add(Conv1D(64, kernel_size=13, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.3, trainable=trainable))
        
        
        model.add(Conv1D(128, kernel_size=17, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(Dropout(rate=0.5, trainable=trainable))


        model.add(Conv1D(256, kernel_size=23, activation='relu',  trainable=trainable))
        model.add(BatchNormalization(trainable=trainable))
        model.add(MaxPooling1D(1, trainable=trainable))
        model.add(GlobalAveragePooling1D(trainable=trainable))

        model.add(Dense(180, activation='elu'))
        model.add(BatchNormalization())
        model.add(Dropout(rate=0.5, trainable=trainable))
        model.add(Dense(150, activation='elu'))
        model.add(BatchNormalization())
        model.add(Dense(nb_classes,name='phenultimate_layer'))
        model.add(Activation('softmax', name='softmax', trainable=trainable))

        return model


In [4]:
import os
import math

import tensorflow as tf
from tensorflow.keras import backend as K


#from Model_DF import DFNet
import random
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.models import Model
import numpy as np
import os
from sklearn.metrics import accuracy_score

snapshot_number=8

#MyAdamW = extend_with_decoupled_weight_decay(Adam)
# Create a MyAdamW object
#OPTIMIZER = MyAdamW(weight_decay=0.001, learning_rate=0.0001,beta_1=0.9, beta_2=0.999)

# ...
learning_rate_data=[]
loss_data=[]


def step_decay(epoch):
   initial_lrate = 0.08
   
   if epoch<2 and i>0:
     lrate=0.1
   
   else:
     lrate = initial_lrate * (0.5+0.5*np.cos(epoch*math.pi/(NB_EPOCH//snapshot_number)))

   learning_rate_data.append(lrate)
   optimizer = model.optimizer
   optimizer.lr = lrate
   return lrate
   
lrate = LearningRateScheduler(step_decay)

random.seed(0)


description = "Training and evaluating DF model for closed-world scenario on non-defended dataset"

print (description)
# Training the DF model
NB_EPOCH = 80   # Number of training epoch
print ("Number of Epoch: ", NB_EPOCH)
BATCH_SIZE = 70 # Batch size
VERBOSE = 2 # Output display mode
LENGTH = 475 # Packet sequence length
OPTIMIZER = Adamax(learning_rate=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.003) # Optimizer

NB_CLASSES = 40 # number of outputs = number of classes
INPUT_SHAPE = (LENGTH,1)


# Data: shuffled and split between train and test sets

print ("Loading and preparing data for training, and evaluating the model")
X_train, y_train, X_valid, y_valid, X_test, y_test = LoadDataIot()
# Please refer to the dataset format in readme

# Convert data as float32 type
X_train = X_train.astype('float32')
X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('float32')
y_valid = y_valid.astype('float32')
y_test = y_test.astype('float32')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
X_train = X_train[:, :,np.newaxis]
X_valid = X_valid[:, :,np.newaxis]
X_test = X_test[:, :,np.newaxis]

print(X_train.shape[0], 'train samples')
print(X_valid.shape[0], 'validation samples')
print(X_test.shape[0], 'test samples')

# Convert class vectors to categorical classes matrices
y_train = to_categorical(y_train, NB_CLASSES)
y_valid = to_categorical(y_valid, NB_CLASSES)
#y_test = to_categorical(y_test, NB_CLASSES)
# Building and training model
# print ("Building and training DF model")

model = DFNet_Add_Layer.build(input_shape=INPUT_SHAPE, nb_classes=NB_CLASSES)

model.compile(loss="categorical_crossentropy", optimizer=OPTIMIZER,
	metrics=["accuracy"])
print ("Model compiled")

filepath = 'IoT.hdf5'

checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint,lrate]

Predictions=[]
# Start training
for i in range(snapshot_number):
  # callbacks_list.append(EarlyStopping(monitor='val_acc', mode='max', patience=6))
  #model.summary()
  
  history = model.fit(X_train, y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH//snapshot_number,verbose=VERBOSE, validation_data=(X_valid, y_valid), callbacks=callbacks_list)
  losss=history.history['val_loss']
  #print(losss.shape)
  loss_data+=losss
  
  Predictions.append(model.predict(X_test))
  
  model2 = Model(model.input, model.layers[-2].output)
  model2.save('snapshot_'+str(i)+'.hdf5')


#model=load_model('AWF.hdf5')

# Start evaluating model with testing data
Predictions=np.array(Predictions)
Avg_prediction=np.average(Predictions,axis=0)
print(Avg_prediction.shape)


Avg_prediction=np.argmax(Avg_prediction,axis=1)
print(Avg_prediction.shape)
        
#print("############## Training is Done Successfully ###################")
#model.save('DC_without_norm.hdf5')

#model=load_model('AWF.hdf5')

# Start evaluating model with testing data
score_test = accuracy_score(Avg_prediction, y_test)
print("Testing closed accuracy_without_norm:", score_test)

lr=history.history['lr']
learning_rate_data=np.array(learning_rate_data)
print(learning_rate_data.shape)
print(learning_rate_data[:10])

loss_data=np.array(loss_data)
print(loss_data.shape)



Training and evaluating DF model for closed-world scenario on non-defended dataset
Number of Epoch:  80
Loading and preparing data for training, and evaluating the model
Data dimensions:
X: Training data's shape :  (41962, 475)
y: Training data's shape :  (41962,)
X: Validation data's shape :  (10790, 475)
y: Validation data's shape :  (10790,)
X: Testing data's shape :  (7194, 475)
y: Testing data's shape :  (7194,)
41962 train samples
10790 validation samples
7194 test samples


2022-06-21 19:26:29.897426: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-21 19:26:30.012771: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-21 19:26:30.013990: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-21 19:26:30.017822: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

Model compiled


2022-06-21 19:26:33.054475: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/10


2022-06-21 19:26:35.849180: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8005


600/600 - 36s - loss: 1.6040 - accuracy: 0.4785 - val_loss: 1.3733 - val_accuracy: 0.5650
Epoch 2/10
600/600 - 25s - loss: 1.0574 - accuracy: 0.6464 - val_loss: 0.8990 - val_accuracy: 0.6945
Epoch 3/10
600/600 - 25s - loss: 0.7954 - accuracy: 0.7398 - val_loss: 0.7444 - val_accuracy: 0.7459
Epoch 4/10
600/600 - 25s - loss: 0.6523 - accuracy: 0.7915 - val_loss: 0.4372 - val_accuracy: 0.8618
Epoch 5/10
600/600 - 25s - loss: 0.5807 - accuracy: 0.8138 - val_loss: 0.4669 - val_accuracy: 0.8543
Epoch 6/10
600/600 - 26s - loss: 0.5204 - accuracy: 0.8330 - val_loss: 0.3484 - val_accuracy: 0.8992
Epoch 7/10
600/600 - 25s - loss: 0.4866 - accuracy: 0.8453 - val_loss: 0.3264 - val_accuracy: 0.9049
Epoch 8/10
600/600 - 25s - loss: 0.4599 - accuracy: 0.8530 - val_loss: 0.2936 - val_accuracy: 0.9187
Epoch 9/10
600/600 - 25s - loss: 0.4493 - accuracy: 0.8587 - val_loss: 0.2832 - val_accuracy: 0.9222
Epoch 10/10
600/600 - 25s - loss: 0.4396 - accuracy: 0.8605 - val_loss: 0.2752 - val_accuracy: 0.9233


In [5]:
X_train, y_train, X_valid, y_valid, X_test, y_test = LoadDataIot()
# Please refer to the dataset format in readme

# Convert data as float32 type
X_train = X_train.astype('float32')
X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('int16')
y_valid = y_valid.astype('int16')
y_test = y_test.astype('int16')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
X_train = X_train[:, :,np.newaxis]
X_valid = X_valid[:, :,np.newaxis]
X_test = X_test[:, :,np.newaxis]

print(X_train.shape[0], 'train samples')
print(X_valid.shape[0], 'validation samples')
print(X_test.shape[0], 'test samples')


#y_test_=np.argmax(y_test_, axis=1)
txt_O = "Mean_{Class1:.0f}"
Means={}
for i in range(NB_CLASSES):
  Means[txt_O.format(Class1=i)]=np.array([0]*NB_CLASSES)
  
dataset_dir='./'

tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model(dataset_dir+'snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_train))
  
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)


print('Shape: ',tflite_model_predictions.shape)
count=[0]*NB_CLASSES

for i in range(len(tflite_model_predictions)):
  k=np.argmax(tflite_model_predictions[i])
  if (np.argmax(tflite_model_predictions[i])==y_train[i]):
    Means[txt_O.format(Class1=y_train[i])]=Means[txt_O.format(Class1=y_train[i])]+tflite_model_predictions[i]
    count[y_train[i]]+=1
#print("Counts: ",count)

Mean_Vectors=[]   
for i in range(NB_CLASSES):
  Means[txt_O.format(Class1=i)]=Means[txt_O.format(Class1=i)]/count[i]
  Mean_Vectors.append(Means[txt_O.format(Class1=i)])

Mean_vectors=np.array(Mean_Vectors)
np.save('Mean_vectors.npy', Mean_vectors, allow_pickle=True)



tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model(dataset_dir+'snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_valid))
    
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)


print('Shape: ',tflite_model_predictions.shape)

txt_1 = "Dist_{Class1:.0f}"
Distances={}
for i in range(NB_CLASSES):
  Distances[txt_1.format(Class1=i)]=[]
  
  
for i in range(len(tflite_model_predictions)):
  if (y_valid[i]==np.argmax(tflite_model_predictions[i])):
    dist = np.linalg.norm(Mean_Vectors[y_valid[i]]-tflite_model_predictions[i])
    Distances[txt_1.format(Class1=y_valid[i])].append(dist)

#print(Distances)    
TH=[0]*NB_CLASSES  
for j in range(NB_CLASSES):
  Distances[txt_1.format(Class1=j)].sort()
  Dist=Distances[txt_1.format(Class1=j)]
  TH[j]=Dist[int(len(Dist)*0.90)]  



Threasholds=np.array(TH)
#print(Threasholds)
np.save('Threasholds_s.npy',Threasholds)


print("Done")




Data dimensions:
X: Training data's shape :  (41962, 475)
y: Training data's shape :  (41962,)
X: Validation data's shape :  (10790, 475)
y: Validation data's shape :  (10790,)
X: Testing data's shape :  (7194, 475)
y: Testing data's shape :  (7194,)
41962 train samples
10790 validation samples
7194 test samples
Shape:  (41962, 40)
Shape:  (10790, 40)
Done


In [6]:


def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(X_train_Rep).batch(1).take(100):
    # Model has only one input so each data point has one element.
    yield [input_value]
    
def Macro_F1(Matrix):
  Precisions=np.zeros(NB_CLASSES)
  Recalls=np.zeros(NB_CLASSES)
  
  epsilon=1e-8
  
  for k in range(len(Precisions)):
    Precisions[k]=Matrix[k][k]/np.sum(Matrix,axis=0)[k]
  #print(Precisions)
    
  Precision=np.average(Precisions)
  print("Precision:",Precision)
    
  for k in range(len(Recalls)):
    Recalls[k]=Matrix[k][k]/np.sum(Matrix,axis=1)[k]
   
  Recall=np.average(Recalls)
  print("Recall:",Recall)

  F1_Score=2*Precision*Recall/(Precision+Recall+epsilon)
  return F1_Score
    
def Micro_F1(matrix):
  epsilon=1e-8
  TP=0
  FP=0
  TN=0
  
  for k in range(NB_CLASSES):
    TP+=matrix[k][k]
    FP+=(np.sum(Matrix,axis=0)[k]-matrix[k][k])
    TN+=(np.sum(Matrix,axis=1)[k]-matrix[k][k])
    
  Micro_Prec=TP/(TP+FP)
  Micro_Rec=TP/(TP+TN)
  print("Micro Precision: ", Micro_Prec)
  print("Micro Recall: ", Micro_Rec)
  Micro_F1=2*Micro_Prec*Micro_Rec/(Micro_Rec+Micro_Prec+epsilon)
  
  return Micro_F1


def New_F1_Score(Matrix):
  Column_sum=np.sum(Matrix,axis=0)
  Raw_sum=np.sum(Matrix,axis=1)
  
  Precision_Differences=[]
  Recall_Differences=[]
  for i in range(NB_CLASSES):
    Precision_Differences.append(np.abs(2*Matrix[i][i]-Column_sum[i]))
    Recall_Differences.append(np.abs(2*Matrix[i][i]-Raw_sum[i]))
  
  Precision_Differences=np.array(Precision_Differences)
  Precision_Differences_Per=Precision_Differences/np.sum(Precision_Differences)
  Recall_Differences=np.array(Recall_Differences)
  Recall_Differences_Per=Recall_Differences/np.sum(Recall_Differences)
  
  #print('Precision_Differences_Per',Precision_Differences_Per)
  #print('Recall_Differences_Per',Recall_Differences_Per)
  
  Precisions=np.zeros(NB_CLASSES)
  Recalls=np.zeros(NB_CLASSES)
  
  epsilon=1e-8
  
  for k in range(len(Precisions)):
    Precisions[k]=(Matrix[k][k]/np.sum(Matrix,axis=0)[k])
  #print(Precisions)
  Precision=np.sum(np.array(Precisions)*Precision_Differences_Per)
  
  for k in range(len(Recalls)):
    Recalls[k]=(Matrix[k][k]/np.sum(Matrix,axis=1)[k])  #*Recall_Differences_Per[k]
  Recall=np.sum(np.array(Recalls)*Recall_Differences_Per)
  
  print('Precision: ',Precision)
  print('Recall: ',Recall)
    
  
  F1_Score=2*Precision*Recall/(Precision+Recall+epsilon)
  return F1_Score





X_open=np.load(dataset_dir+'X_open.npy')
X_open=X_open[:,:1500]
y_open = np.array([NB_CLASSES]*len(X_open))

X_test,y_test=shuffle(X_test, y_test)
#X_open,y_open=shuffle(X_open, y_open)

#X_open=X_open[:5000]
#y_open=y_open[:5000]


print("X_open shape:", X_open.shape)
#print(X_test[0])


# Convert data as float32 type
#X_train = X_train.astype('float32')
#X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
X_open = X_open.astype('float32')
#y_train = y_train.astype('float32')
#y_valid = y_valid.astype('float32')
y_test = y_test.astype('int16')
#y_open = y_open.astype('int8')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
#X_train = X_train[:, :,np.newaxis]
#X_valid = X_valid[:, :,np.newaxis]


print()
#print(X_train[0])
#print(X_valid[0])
#print("################################")
#print(X_test[0])

#model=load_model('IoT_without_softmax_Robust_Addlayer_s10.hdf5')
Mean_Vectors=np.load('Mean_vectors.npy')
Threasholds=np.load('Threasholds_s.npy')




X_open = X_open[:, :,np.newaxis]


prediction_classes=[]
tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model('snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_test))
  
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)

for i in range(len(tflite_model_predictions)):
  
    d=np.argmax(tflite_model_predictions[i], axis=0)
    if np.linalg.norm(tflite_model_predictions[i]-Mean_Vectors[d])>Threasholds[d]:
      prediction_classes.append(NB_CLASSES)
      
    else:
      prediction_classes.append(d)
      

    

prediction_classes_open=[]
tflite_model_predictions_open=[]
for i in range(snapshot_number):
  model=load_model('snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions_open.append(model.predict(X_open))
  
tflite_model_predictions_open=np.array(tflite_model_predictions_open)
tflite_model_predictions_open=np.average(tflite_model_predictions_open,axis=0)

for i in range(len(tflite_model_predictions_open)):
    d=np.argmax(tflite_model_predictions_open[i], axis=0)
    if np.linalg.norm(tflite_model_predictions_open[i]-Mean_Vectors[d])>Threasholds[d]:
      prediction_classes_open.append(NB_CLASSES)
      
    else:
      prediction_classes_open.append(d)
      
    
    
acc_Close = accuracy_score(prediction_classes, y_test)
print('Test accuracy TFLITE model_Closed_set :', acc_Close)

acc_Open = accuracy_score(prediction_classes_open, y_open)
print('Test accuracy TFLITE model_Open_set :', acc_Open)


Matrix=[]
for i in range(NB_CLASSES+1):
  Matrix.append(np.zeros(NB_CLASSES+1))
  
  
for i in range(len(y_test)):
  Matrix[y_test[i]][prediction_classes[i]]+=1
  
for i in range(len(y_open)):
  Matrix[y_open[i]][prediction_classes_open[i]]+=1
  
#print(Matrix)




F1_Score=New_F1_Score(Matrix)


#print("Average Precision: ", Precision)
#print("Average Recall: ", Recall)
print("Average F1_Score: ", F1_Score)

print()
print("Micro")
print('Test accuracy TFLITE model_Closed_set :', acc_Close)
print('Test accuracy TFLITE model_Open_set :', acc_Open)
F1_Score=Micro_F1(Matrix)
print("Average F1_Score: ", F1_Score)

print()
print("Macro")
print('Test accuracy TFLITE model_Closed_set :', acc_Close)
print('Test accuracy TFLITE model_Open_set :', acc_Open)
F1_Score=Macro_F1(Matrix)
print("Average F1_Score: ", F1_Score)
print()


X_open shape: (86795, 475)

Test accuracy TFLITE model_Closed_set : 0.8696135668612733
Test accuracy TFLITE model_Open_set : 0.5885131632006452
Precision:  0.12099768074590468
Recall:  0.8731659174364073
Average F1_Score:  0.21254258362834952

Micro
Test accuracy TFLITE model_Closed_set : 0.8696135668612733
Test accuracy TFLITE model_Open_set : 0.5885131632006452
Micro Precision:  0.1486798013166338
Micro Recall:  0.8696135668612733
Average F1_Score:  0.25394247888469385

Macro
Test accuracy TFLITE model_Closed_set : 0.8696135668612733
Test accuracy TFLITE model_Open_set : 0.5885131632006452
Precision: 0.2740197322870187
Recall: 0.8695997184602374
Average F1_Score:  0.4167251261947587



In [7]:
print("################################################################################")

################################################################################


In [8]:
import json
import numpy as np
from tensorflow.keras.utils import to_categorical
import json
import pickle
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


def Exchange_classes(c1,c2,y):
  for i in range(len(y)):
    if y[i]==c1:
      y[i]=c2
      
    elif y[i]==c2:
      y[i]=c1


def balance_dataset(X,y):
  Classes=int(np.max(y))+1
  k=len(y)//Classes-1
  X_=list(np.zeros(k*Classes))
  y_=list(np.zeros(k*Classes))
  
  
  for j in range(Classes):
    for i in range(k):
      y_[i*Classes+j]=j
      Index=list(y).index(j)
      X_[i*Classes+j]=X[Index]
      y[Index]=1000
  
  y=np.array(y_)
  X=np.array(X_)
  return X,y
  
def Filter_close_set(Split_Number,data):
  closed_set=data[Split_Number]["closed"]
  open_set=data[Split_Number]["open"]
  X_5=[]
  X_open=[]
  y_5=[]
  y_open=[]
  for i in range(len(y)):
    if y[i] in closed_set:
      y_5.append(closed_set.index(y[i]))
      X_5.append(X[i])
    else:
      y_open.append(40)
      X_open.append(X[i])
      
  return X_5,X_open,y_5,y_open
  
  
f = open('../input/sydney-data/IOT_data_file.json')
data = json.load(f)
print(data["1"])  


dataset_dir = "../input/sydney-data/dataset/"
X_train = np.load(dataset_dir+'X_train.npy')
print(X_train.shape)
y_train = np.load(dataset_dir+'y_train.npy')
#print(list(y_train).count(0),list(y_train).count(1),list(y_train).count(2),list(y_train).count(3),list(y_train).count(4),list(y_train).count(5),list(y_train).count(6),list(y_train).count(7),list(y_train).count(8),list(y_train).count(9))

    # Load testing data
X_test = np.load(dataset_dir+'X_test.npy')
y_test = np.load(dataset_dir+'y_test.npy')


    # Load testing data
X_valid = np.load(dataset_dir+'X_valid.npy')
y_valid = np.load(dataset_dir+'y_valid.npy')

X=np.concatenate((X_train, X_test,X_valid), axis=0)
y=np.concatenate((y_train, y_test,y_valid), axis=0)

  
#X,y=balance_dataset(X,y)

print(X.shape)
print(y.shape)
print(X[:5])



Split_Number="7"
  
  
X_5,X_open,y_5,y_open=Filter_close_set(Split_Number,data)


  
X_train_5, X_valid_5, y_train_5, y_valid_5 = train_test_split(X_5, y_5, test_size=0.3, shuffle=False)
X_valid_5, X_test_5, y_valid_5, y_test_5 = train_test_split(X_valid_5, y_valid_5, test_size=0.4, shuffle=False)

X_train_5,y_train_5=shuffle(X_train_5, y_train_5)
X_valid_5,y_valid_5=shuffle(X_valid_5, y_valid_5)
X_test_5,y_test_5=shuffle(X_test_5, y_test_5)


X_train_5=np.array(X_train_5)
X_valid_5=np.array(X_valid_5)
X_test_5=np.array(X_test_5)
y_train_5=np.array(y_train_5)
y_valid_5=np.array(y_valid_5)
y_test_5=np.array(y_test_5)
X_open=np.array(X_open)
y_open=np.array(y_open)


#print(y_test)
#print("##############")
#print(y_test_5)

print ("Data dimensions:")
print ("X: Training data's shape : ", X_train_5.shape)
print ("X: Validating data's shape : ", X_valid_5.shape)
print ("X: Testing data's shape : ", X_test_5.shape)
print ("X: open data's shape : ", X_open.shape)
    
np.save('X_train_5.npy',X_train_5)
np.save('X_valid_5.npy',X_valid_5)
np.save('X_test_5.npy',X_test_5)
np.save('y_valid_5.npy',y_valid_5)
np.save('y_train_5.npy',y_train_5)
np.save('y_test_5.npy',y_test_5)
np.save('X_open.npy',X_open)
np.save('y_open.npy',y_open)

#print(y_train_5[:50])
#print()
#print(y_valid_5[:50])
#print()
#print(y_test_5[:50])
#print()
#print(y_open[:50])
#print()

{'closed': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], 'open': [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]}
(88044, 475)
(146741, 475)
(146741,)
[[ 1.  1.  1. ...  0.  0.  0.]
 [ 1. -1. -1. ...  0.  0.  0.]
 [ 1.  1.  1. ...  0.  0.  0.]
 [-1. -1. -1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]]
Data dimensions:
X: Training data's shape :  (41960, 475)
X: Validating data's shape :  (10790, 475)
X: Testing data's shape :  (7194, 475)
X: open data's shape :  (86797, 475)


In [9]:
import os
import math

import tensorflow as tf
from tensorflow.keras import backend as K


#from Model_DF import DFNet
import random
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.models import Model
import numpy as np
import os
from sklearn.metrics import accuracy_score

snapshot_number=8

#MyAdamW = extend_with_decoupled_weight_decay(Adam)
# Create a MyAdamW object
#OPTIMIZER = MyAdamW(weight_decay=0.001, learning_rate=0.0001,beta_1=0.9, beta_2=0.999)

# ...
learning_rate_data=[]
loss_data=[]


def step_decay(epoch):
   initial_lrate = 0.08
   
   if epoch<2 and i>0:
     lrate=0.1
   
   else:
     lrate = initial_lrate * (0.5+0.5*np.cos(epoch*math.pi/(NB_EPOCH//snapshot_number)))

   learning_rate_data.append(lrate)
   optimizer = model.optimizer
   optimizer.lr = lrate
   return lrate
   
lrate = LearningRateScheduler(step_decay)

random.seed(0)


description = "Training and evaluating DF model for closed-world scenario on non-defended dataset"

print (description)
# Training the DF model
NB_EPOCH = 80   # Number of training epoch
print ("Number of Epoch: ", NB_EPOCH)
BATCH_SIZE = 70 # Batch size
VERBOSE = 2 # Output display mode
LENGTH = 475 # Packet sequence length
OPTIMIZER = Adamax(learning_rate=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.003) # Optimizer

NB_CLASSES = 40 # number of outputs = number of classes
INPUT_SHAPE = (LENGTH,1)


# Data: shuffled and split between train and test sets

print ("Loading and preparing data for training, and evaluating the model")
X_train, y_train, X_valid, y_valid, X_test, y_test = LoadDataIot()
# Please refer to the dataset format in readme

# Convert data as float32 type
X_train = X_train.astype('float32')
X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('float32')
y_valid = y_valid.astype('float32')
y_test = y_test.astype('float32')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
X_train = X_train[:, :,np.newaxis]
X_valid = X_valid[:, :,np.newaxis]
X_test = X_test[:, :,np.newaxis]

print(X_train.shape[0], 'train samples')
print(X_valid.shape[0], 'validation samples')
print(X_test.shape[0], 'test samples')

# Convert class vectors to categorical classes matrices
y_train = to_categorical(y_train, NB_CLASSES)
y_valid = to_categorical(y_valid, NB_CLASSES)
#y_test = to_categorical(y_test, NB_CLASSES)
# Building and training model
# print ("Building and training DF model")

model = DFNet_Add_Layer.build(input_shape=INPUT_SHAPE, nb_classes=NB_CLASSES)

model.compile(loss="categorical_crossentropy", optimizer=OPTIMIZER,
	metrics=["accuracy"])
print ("Model compiled")

filepath = 'IoT.hdf5'

checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint,lrate]

Predictions=[]
# Start training
for i in range(snapshot_number):
  # callbacks_list.append(EarlyStopping(monitor='val_acc', mode='max', patience=6))
  #model.summary()
  
  history = model.fit(X_train, y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH//snapshot_number,verbose=VERBOSE, validation_data=(X_valid, y_valid), callbacks=callbacks_list)
  losss=history.history['val_loss']
  #print(losss.shape)
  loss_data+=losss
  
  Predictions.append(model.predict(X_test))
  
  model2 = Model(model.input, model.layers[-2].output)
  model2.save('snapshot_'+str(i)+'.hdf5')


#model=load_model('AWF.hdf5')

# Start evaluating model with testing data
Predictions=np.array(Predictions)
Avg_prediction=np.average(Predictions,axis=0)
print(Avg_prediction.shape)


Avg_prediction=np.argmax(Avg_prediction,axis=1)
print(Avg_prediction.shape)
        
#print("############## Training is Done Successfully ###################")
#model.save('DC_without_norm.hdf5')

#model=load_model('AWF.hdf5')

# Start evaluating model with testing data
score_test = accuracy_score(Avg_prediction, y_test)
print("Testing closed accuracy_without_norm:", score_test)

lr=history.history['lr']
learning_rate_data=np.array(learning_rate_data)
print(learning_rate_data.shape)
print(learning_rate_data[:10])

loss_data=np.array(loss_data)
print(loss_data.shape)



Training and evaluating DF model for closed-world scenario on non-defended dataset
Number of Epoch:  80
Loading and preparing data for training, and evaluating the model
Data dimensions:
X: Training data's shape :  (41960, 475)
y: Training data's shape :  (41960,)
X: Validation data's shape :  (10790, 475)
y: Validation data's shape :  (10790,)
X: Testing data's shape :  (7194, 475)
y: Testing data's shape :  (7194,)
41960 train samples
10790 validation samples
7194 test samples
Model compiled
Epoch 1/10
600/600 - 28s - loss: 1.6055 - accuracy: 0.4944 - val_loss: 1.1106 - val_accuracy: 0.6350
Epoch 2/10
600/600 - 25s - loss: 1.0641 - accuracy: 0.6539 - val_loss: 0.8302 - val_accuracy: 0.7375
Epoch 3/10
600/600 - 25s - loss: 0.8622 - accuracy: 0.7192 - val_loss: 0.6340 - val_accuracy: 0.8024
Epoch 4/10
600/600 - 25s - loss: 0.7554 - accuracy: 0.7565 - val_loss: 0.4960 - val_accuracy: 0.8467
Epoch 5/10
600/600 - 25s - loss: 0.6606 - accuracy: 0.7920 - val_loss: 0.4225 - val_accuracy: 0.8

In [10]:
X_train, y_train, X_valid, y_valid, X_test, y_test = LoadDataIot()
# Please refer to the dataset format in readme

# Convert data as float32 type
X_train = X_train.astype('float32')
X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('int16')
y_valid = y_valid.astype('int16')
y_test = y_test.astype('int16')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
X_train = X_train[:, :,np.newaxis]
X_valid = X_valid[:, :,np.newaxis]
X_test = X_test[:, :,np.newaxis]

print(X_train.shape[0], 'train samples')
print(X_valid.shape[0], 'validation samples')
print(X_test.shape[0], 'test samples')


#y_test_=np.argmax(y_test_, axis=1)
txt_O = "Mean_{Class1:.0f}"
Means={}
for i in range(NB_CLASSES):
  Means[txt_O.format(Class1=i)]=np.array([0]*NB_CLASSES)
  
dataset_dir='./'

tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model(dataset_dir+'snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_train))
  
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)


print('Shape: ',tflite_model_predictions.shape)
count=[0]*NB_CLASSES

for i in range(len(tflite_model_predictions)):
  k=np.argmax(tflite_model_predictions[i])
  if (np.argmax(tflite_model_predictions[i])==y_train[i]):
    Means[txt_O.format(Class1=y_train[i])]=Means[txt_O.format(Class1=y_train[i])]+tflite_model_predictions[i]
    count[y_train[i]]+=1
#print("Counts: ",count)

Mean_Vectors=[]   
for i in range(NB_CLASSES):
  Means[txt_O.format(Class1=i)]=Means[txt_O.format(Class1=i)]/count[i]
  Mean_Vectors.append(Means[txt_O.format(Class1=i)])

Mean_vectors=np.array(Mean_Vectors)
np.save('Mean_vectors.npy', Mean_vectors, allow_pickle=True)



tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model(dataset_dir+'snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_valid))
    
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)


print('Shape: ',tflite_model_predictions.shape)

txt_1 = "Dist_{Class1:.0f}"
Distances={}
for i in range(NB_CLASSES):
  Distances[txt_1.format(Class1=i)]=[]
  
  
for i in range(len(tflite_model_predictions)):
  if (y_valid[i]==np.argmax(tflite_model_predictions[i])):
    dist = np.linalg.norm(Mean_Vectors[y_valid[i]]-tflite_model_predictions[i])
    Distances[txt_1.format(Class1=y_valid[i])].append(dist)

#print(Distances)    
TH=[0]*NB_CLASSES  
for j in range(NB_CLASSES):
  Distances[txt_1.format(Class1=j)].sort()
  Dist=Distances[txt_1.format(Class1=j)]
  TH[j]=Dist[int(len(Dist)*0.90)]  



Threasholds=np.array(TH)
#print(Threasholds)
np.save('Threasholds_s.npy',Threasholds)


print("Done")




Data dimensions:
X: Training data's shape :  (41960, 475)
y: Training data's shape :  (41960,)
X: Validation data's shape :  (10790, 475)
y: Validation data's shape :  (10790,)
X: Testing data's shape :  (7194, 475)
y: Testing data's shape :  (7194,)
41960 train samples
10790 validation samples
7194 test samples
Shape:  (41960, 40)
Shape:  (10790, 40)
Done


In [11]:


def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(X_train_Rep).batch(1).take(100):
    # Model has only one input so each data point has one element.
    yield [input_value]
    
def Macro_F1(Matrix):
  Precisions=np.zeros(NB_CLASSES)
  Recalls=np.zeros(NB_CLASSES)
  
  epsilon=1e-8
  
  for k in range(len(Precisions)):
    Precisions[k]=Matrix[k][k]/np.sum(Matrix,axis=0)[k]
  #print(Precisions)
    
  Precision=np.average(Precisions)
  print("Precision:",Precision)
    
  for k in range(len(Recalls)):
    Recalls[k]=Matrix[k][k]/np.sum(Matrix,axis=1)[k]
   
  Recall=np.average(Recalls)
  print("Recall:",Recall)

  F1_Score=2*Precision*Recall/(Precision+Recall+epsilon)
  return F1_Score
    
def Micro_F1(matrix):
  epsilon=1e-8
  TP=0
  FP=0
  TN=0
  
  for k in range(NB_CLASSES):
    TP+=matrix[k][k]
    FP+=(np.sum(Matrix,axis=0)[k]-matrix[k][k])
    TN+=(np.sum(Matrix,axis=1)[k]-matrix[k][k])
    
  Micro_Prec=TP/(TP+FP)
  Micro_Rec=TP/(TP+TN)
  print("Micro Precision: ", Micro_Prec)
  print("Micro Recall: ", Micro_Rec)
  Micro_F1=2*Micro_Prec*Micro_Rec/(Micro_Rec+Micro_Prec+epsilon)
  
  return Micro_F1


def New_F1_Score(Matrix):
  Column_sum=np.sum(Matrix,axis=0)
  Raw_sum=np.sum(Matrix,axis=1)
  
  Precision_Differences=[]
  Recall_Differences=[]
  for i in range(NB_CLASSES):
    Precision_Differences.append(np.abs(2*Matrix[i][i]-Column_sum[i]))
    Recall_Differences.append(np.abs(2*Matrix[i][i]-Raw_sum[i]))
  
  Precision_Differences=np.array(Precision_Differences)
  Precision_Differences_Per=Precision_Differences/np.sum(Precision_Differences)
  Recall_Differences=np.array(Recall_Differences)
  Recall_Differences_Per=Recall_Differences/np.sum(Recall_Differences)
  
  #print('Precision_Differences_Per',Precision_Differences_Per)
  #print('Recall_Differences_Per',Recall_Differences_Per)
  
  Precisions=np.zeros(NB_CLASSES)
  Recalls=np.zeros(NB_CLASSES)
  
  epsilon=1e-8
  
  for k in range(len(Precisions)):
    Precisions[k]=(Matrix[k][k]/np.sum(Matrix,axis=0)[k])
  #print(Precisions)
  Precision=np.sum(np.array(Precisions)*Precision_Differences_Per)
  
  for k in range(len(Recalls)):
    Recalls[k]=(Matrix[k][k]/np.sum(Matrix,axis=1)[k])  #*Recall_Differences_Per[k]
  Recall=np.sum(np.array(Recalls)*Recall_Differences_Per)
  
  print('Precision: ',Precision)
  print('Recall: ',Recall)
    
  
  F1_Score=2*Precision*Recall/(Precision+Recall+epsilon)
  return F1_Score





X_open=np.load(dataset_dir+'X_open.npy')
X_open=X_open[:,:1500]
y_open = np.array([NB_CLASSES]*len(X_open))

X_test,y_test=shuffle(X_test, y_test)
#X_open,y_open=shuffle(X_open, y_open)

#X_open=X_open[:5000]
#y_open=y_open[:5000]


print("X_open shape:", X_open.shape)
#print(X_test[0])


# Convert data as float32 type
#X_train = X_train.astype('float32')
#X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
X_open = X_open.astype('float32')
#y_train = y_train.astype('float32')
#y_valid = y_valid.astype('float32')
y_test = y_test.astype('int16')
#y_open = y_open.astype('int8')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
#X_train = X_train[:, :,np.newaxis]
#X_valid = X_valid[:, :,np.newaxis]


print()
#print(X_train[0])
#print(X_valid[0])
#print("################################")
#print(X_test[0])

#model=load_model('IoT_without_softmax_Robust_Addlayer_s10.hdf5')
Mean_Vectors=np.load('Mean_vectors.npy')
Threasholds=np.load('Threasholds_s.npy')




X_open = X_open[:, :,np.newaxis]


prediction_classes=[]
tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model('snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_test))
  
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)

for i in range(len(tflite_model_predictions)):
  
    d=np.argmax(tflite_model_predictions[i], axis=0)
    if np.linalg.norm(tflite_model_predictions[i]-Mean_Vectors[d])>Threasholds[d]:
      prediction_classes.append(NB_CLASSES)
      
    else:
      prediction_classes.append(d)
      

    

prediction_classes_open=[]
tflite_model_predictions_open=[]
for i in range(snapshot_number):
  model=load_model('snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions_open.append(model.predict(X_open))
  
tflite_model_predictions_open=np.array(tflite_model_predictions_open)
tflite_model_predictions_open=np.average(tflite_model_predictions_open,axis=0)

for i in range(len(tflite_model_predictions_open)):
    d=np.argmax(tflite_model_predictions_open[i], axis=0)
    if np.linalg.norm(tflite_model_predictions_open[i]-Mean_Vectors[d])>Threasholds[d]:
      prediction_classes_open.append(NB_CLASSES)
      
    else:
      prediction_classes_open.append(d)
      
    
    
acc_Close = accuracy_score(prediction_classes, y_test)
print('Test accuracy TFLITE model_Closed_set :', acc_Close)

acc_Open = accuracy_score(prediction_classes_open, y_open)
print('Test accuracy TFLITE model_Open_set :', acc_Open)


Matrix=[]
for i in range(NB_CLASSES+1):
  Matrix.append(np.zeros(NB_CLASSES+1))
  
  
for i in range(len(y_test)):
  Matrix[y_test[i]][prediction_classes[i]]+=1
  
for i in range(len(y_open)):
  Matrix[y_open[i]][prediction_classes_open[i]]+=1
  
#print(Matrix)




F1_Score=New_F1_Score(Matrix)


#print("Average Precision: ", Precision)
#print("Average Recall: ", Recall)
print("Average F1_Score: ", F1_Score)

print()
print("Micro")
print('Test accuracy TFLITE model_Closed_set :', acc_Close)
print('Test accuracy TFLITE model_Open_set :', acc_Open)
F1_Score=Micro_F1(Matrix)
print("Average F1_Score: ", F1_Score)

print()
print("Macro")
print('Test accuracy TFLITE model_Closed_set :', acc_Close)
print('Test accuracy TFLITE model_Open_set :', acc_Open)
F1_Score=Macro_F1(Matrix)
print("Average F1_Score: ", F1_Score)
print()


X_open shape: (86797, 475)

Test accuracy TFLITE model_Closed_set : 0.8577981651376146
Test accuracy TFLITE model_Open_set : 0.5954929317833566
Precision:  0.11652959621233752
Recall:  0.8637789753277099
Average F1_Score:  0.20535536892580533

Micro
Test accuracy TFLITE model_Closed_set : 0.8577981651376146
Test accuracy TFLITE model_Open_set : 0.5954929317833566
Micro Precision:  0.1489428461092875
Micro Recall:  0.8577981651376146
Average F1_Score:  0.25381482905043407

Macro
Test accuracy TFLITE model_Closed_set : 0.8577981651376146
Test accuracy TFLITE model_Open_set : 0.5954929317833566
Precision: 0.23673931529840697
Recall: 0.857742406110723
Average F1_Score:  0.37106393665177406



In [12]:
print("##########################################################################################")

##########################################################################################


In [13]:
import json
import numpy as np
from tensorflow.keras.utils import to_categorical
import json
import pickle
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


def Exchange_classes(c1,c2,y):
  for i in range(len(y)):
    if y[i]==c1:
      y[i]=c2
      
    elif y[i]==c2:
      y[i]=c1


def balance_dataset(X,y):
  Classes=int(np.max(y))+1
  k=len(y)//Classes-1
  X_=list(np.zeros(k*Classes))
  y_=list(np.zeros(k*Classes))
  
  
  for j in range(Classes):
    for i in range(k):
      y_[i*Classes+j]=j
      Index=list(y).index(j)
      X_[i*Classes+j]=X[Index]
      y[Index]=1000
  
  y=np.array(y_)
  X=np.array(X_)
  return X,y
  
def Filter_close_set(Split_Number,data):
  closed_set=data[Split_Number]["closed"]
  open_set=data[Split_Number]["open"]
  X_5=[]
  X_open=[]
  y_5=[]
  y_open=[]
  for i in range(len(y)):
    if y[i] in closed_set:
      y_5.append(closed_set.index(y[i]))
      X_5.append(X[i])
    else:
      y_open.append(40)
      X_open.append(X[i])
      
  return X_5,X_open,y_5,y_open
  
  
f = open('../input/sydney-data/IOT_data_file.json')
data = json.load(f)
print(data["1"])  


dataset_dir = "../input/sydney-data/dataset/"
X_train = np.load(dataset_dir+'X_train.npy')
print(X_train.shape)
y_train = np.load(dataset_dir+'y_train.npy')
#print(list(y_train).count(0),list(y_train).count(1),list(y_train).count(2),list(y_train).count(3),list(y_train).count(4),list(y_train).count(5),list(y_train).count(6),list(y_train).count(7),list(y_train).count(8),list(y_train).count(9))

    # Load testing data
X_test = np.load(dataset_dir+'X_test.npy')
y_test = np.load(dataset_dir+'y_test.npy')


    # Load testing data
X_valid = np.load(dataset_dir+'X_valid.npy')
y_valid = np.load(dataset_dir+'y_valid.npy')

X=np.concatenate((X_train, X_test,X_valid), axis=0)
y=np.concatenate((y_train, y_test,y_valid), axis=0)

  
#X,y=balance_dataset(X,y)

print(X.shape)
print(y.shape)
print(X[:5])



Split_Number="8"
  
  
X_5,X_open,y_5,y_open=Filter_close_set(Split_Number,data)


  
X_train_5, X_valid_5, y_train_5, y_valid_5 = train_test_split(X_5, y_5, test_size=0.3, shuffle=False)
X_valid_5, X_test_5, y_valid_5, y_test_5 = train_test_split(X_valid_5, y_valid_5, test_size=0.4, shuffle=False)

X_train_5,y_train_5=shuffle(X_train_5, y_train_5)
X_valid_5,y_valid_5=shuffle(X_valid_5, y_valid_5)
X_test_5,y_test_5=shuffle(X_test_5, y_test_5)


X_train_5=np.array(X_train_5)
X_valid_5=np.array(X_valid_5)
X_test_5=np.array(X_test_5)
y_train_5=np.array(y_train_5)
y_valid_5=np.array(y_valid_5)
y_test_5=np.array(y_test_5)
X_open=np.array(X_open)
y_open=np.array(y_open)


#print(y_test)
#print("##############")
#print(y_test_5)

print ("Data dimensions:")
print ("X: Training data's shape : ", X_train_5.shape)
print ("X: Validating data's shape : ", X_valid_5.shape)
print ("X: Testing data's shape : ", X_test_5.shape)
print ("X: open data's shape : ", X_open.shape)
    
np.save('X_train_5.npy',X_train_5)
np.save('X_valid_5.npy',X_valid_5)
np.save('X_test_5.npy',X_test_5)
np.save('y_valid_5.npy',y_valid_5)
np.save('y_train_5.npy',y_train_5)
np.save('y_test_5.npy',y_test_5)
np.save('X_open.npy',X_open)
np.save('y_open.npy',y_open)

#print(y_train_5[:50])
#print()
#print(y_valid_5[:50])
#print()
#print(y_test_5[:50])
#print()
#print(y_open[:50])
#print()

{'closed': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], 'open': [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]}
(88044, 475)
(146741, 475)
(146741,)
[[ 1.  1.  1. ...  0.  0.  0.]
 [ 1. -1. -1. ...  0.  0.  0.]
 [ 1.  1.  1. ...  0.  0.  0.]
 [-1. -1. -1. ...  0.  0.  0.]
 [ 1. -1.  1. ...  0.  0.  0.]]
Data dimensions:
X: Training data's shape :  (41928, 475)
X: Validating data's shape :  (10782, 475)
X: Testing data's shape :  (7188, 475)
X: open data's shape :  (86843, 475)


In [14]:
import os
import math

import tensorflow as tf
from tensorflow.keras import backend as K


#from Model_DF import DFNet
import random
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adamax
from tensorflow.keras.models import Model
import numpy as np
import os
from sklearn.metrics import accuracy_score

snapshot_number=8

#MyAdamW = extend_with_decoupled_weight_decay(Adam)
# Create a MyAdamW object
#OPTIMIZER = MyAdamW(weight_decay=0.001, learning_rate=0.0001,beta_1=0.9, beta_2=0.999)

# ...
learning_rate_data=[]
loss_data=[]


def step_decay(epoch):
   initial_lrate = 0.08
   
   if epoch<2 and i>0:
     lrate=0.1
   
   else:
     lrate = initial_lrate * (0.5+0.5*np.cos(epoch*math.pi/(NB_EPOCH//snapshot_number)))

   learning_rate_data.append(lrate)
   optimizer = model.optimizer
   optimizer.lr = lrate
   return lrate
   
lrate = LearningRateScheduler(step_decay)

random.seed(0)


description = "Training and evaluating DF model for closed-world scenario on non-defended dataset"

print (description)
# Training the DF model
NB_EPOCH = 80   # Number of training epoch
print ("Number of Epoch: ", NB_EPOCH)
BATCH_SIZE = 70 # Batch size
VERBOSE = 2 # Output display mode
LENGTH = 475 # Packet sequence length
OPTIMIZER = Adamax(learning_rate=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.003) # Optimizer

NB_CLASSES = 40 # number of outputs = number of classes
INPUT_SHAPE = (LENGTH,1)


# Data: shuffled and split between train and test sets

print ("Loading and preparing data for training, and evaluating the model")
X_train, y_train, X_valid, y_valid, X_test, y_test = LoadDataIot()
# Please refer to the dataset format in readme

# Convert data as float32 type
X_train = X_train.astype('float32')
X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('float32')
y_valid = y_valid.astype('float32')
y_test = y_test.astype('float32')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
X_train = X_train[:, :,np.newaxis]
X_valid = X_valid[:, :,np.newaxis]
X_test = X_test[:, :,np.newaxis]

print(X_train.shape[0], 'train samples')
print(X_valid.shape[0], 'validation samples')
print(X_test.shape[0], 'test samples')

# Convert class vectors to categorical classes matrices
y_train = to_categorical(y_train, NB_CLASSES)
y_valid = to_categorical(y_valid, NB_CLASSES)
#y_test = to_categorical(y_test, NB_CLASSES)
# Building and training model
# print ("Building and training DF model")

model = DFNet_Add_Layer.build(input_shape=INPUT_SHAPE, nb_classes=NB_CLASSES)

model.compile(loss="categorical_crossentropy", optimizer=OPTIMIZER,
	metrics=["accuracy"])
print ("Model compiled")

filepath = 'IoT.hdf5'

checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint,lrate]

Predictions=[]
# Start training
for i in range(snapshot_number):
  # callbacks_list.append(EarlyStopping(monitor='val_acc', mode='max', patience=6))
  #model.summary()
  
  history = model.fit(X_train, y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH//snapshot_number,verbose=VERBOSE, validation_data=(X_valid, y_valid), callbacks=callbacks_list)
  losss=history.history['val_loss']
  #print(losss.shape)
  loss_data+=losss
  
  Predictions.append(model.predict(X_test))
  
  model2 = Model(model.input, model.layers[-2].output)
  model2.save('snapshot_'+str(i)+'.hdf5')


#model=load_model('AWF.hdf5')

# Start evaluating model with testing data
Predictions=np.array(Predictions)
Avg_prediction=np.average(Predictions,axis=0)
print(Avg_prediction.shape)


Avg_prediction=np.argmax(Avg_prediction,axis=1)
print(Avg_prediction.shape)
        
#print("############## Training is Done Successfully ###################")
#model.save('DC_without_norm.hdf5')

#model=load_model('AWF.hdf5')

# Start evaluating model with testing data
score_test = accuracy_score(Avg_prediction, y_test)
print("Testing closed accuracy_without_norm:", score_test)

lr=history.history['lr']
learning_rate_data=np.array(learning_rate_data)
print(learning_rate_data.shape)
print(learning_rate_data[:10])

loss_data=np.array(loss_data)
print(loss_data.shape)




Training and evaluating DF model for closed-world scenario on non-defended dataset
Number of Epoch:  80
Loading and preparing data for training, and evaluating the model
Data dimensions:
X: Training data's shape :  (41928, 475)
y: Training data's shape :  (41928,)
X: Validation data's shape :  (10782, 475)
y: Validation data's shape :  (10782,)
X: Testing data's shape :  (7188, 475)
y: Testing data's shape :  (7188,)
41928 train samples
10782 validation samples
7188 test samples
Model compiled
Epoch 1/10
599/599 - 28s - loss: 1.7261 - accuracy: 0.4642 - val_loss: 1.1798 - val_accuracy: 0.6284
Epoch 2/10
599/599 - 25s - loss: 1.1439 - accuracy: 0.6361 - val_loss: 0.9522 - val_accuracy: 0.6922
Epoch 3/10
599/599 - 25s - loss: 0.9173 - accuracy: 0.7082 - val_loss: 0.6990 - val_accuracy: 0.7852
Epoch 4/10
599/599 - 25s - loss: 0.8047 - accuracy: 0.7470 - val_loss: 0.5341 - val_accuracy: 0.8443
Epoch 5/10
599/599 - 25s - loss: 0.6928 - accuracy: 0.7818 - val_loss: 0.5525 - val_accuracy: 0.8

In [15]:
X_train, y_train, X_valid, y_valid, X_test, y_test = LoadDataIot()
# Please refer to the dataset format in readme

# Convert data as float32 type
X_train = X_train.astype('float32')
X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('int16')
y_valid = y_valid.astype('int16')
y_test = y_test.astype('int16')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
X_train = X_train[:, :,np.newaxis]
X_valid = X_valid[:, :,np.newaxis]
X_test = X_test[:, :,np.newaxis]

print(X_train.shape[0], 'train samples')
print(X_valid.shape[0], 'validation samples')
print(X_test.shape[0], 'test samples')


#y_test_=np.argmax(y_test_, axis=1)
txt_O = "Mean_{Class1:.0f}"
Means={}
for i in range(NB_CLASSES):
  Means[txt_O.format(Class1=i)]=np.array([0]*NB_CLASSES)
  
dataset_dir='./'

tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model(dataset_dir+'snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_train))
  
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)


print('Shape: ',tflite_model_predictions.shape)
count=[0]*NB_CLASSES

for i in range(len(tflite_model_predictions)):
  k=np.argmax(tflite_model_predictions[i])
  if (np.argmax(tflite_model_predictions[i])==y_train[i]):
    Means[txt_O.format(Class1=y_train[i])]=Means[txt_O.format(Class1=y_train[i])]+tflite_model_predictions[i]
    count[y_train[i]]+=1
#print("Counts: ",count)

Mean_Vectors=[]   
for i in range(NB_CLASSES):
  Means[txt_O.format(Class1=i)]=Means[txt_O.format(Class1=i)]/count[i]
  Mean_Vectors.append(Means[txt_O.format(Class1=i)])

Mean_vectors=np.array(Mean_Vectors)
np.save('Mean_vectors.npy', Mean_vectors, allow_pickle=True)



tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model(dataset_dir+'snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_valid))
    
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)


print('Shape: ',tflite_model_predictions.shape)

txt_1 = "Dist_{Class1:.0f}"
Distances={}
for i in range(NB_CLASSES):
  Distances[txt_1.format(Class1=i)]=[]
  
  
for i in range(len(tflite_model_predictions)):
  if (y_valid[i]==np.argmax(tflite_model_predictions[i])):
    dist = np.linalg.norm(Mean_Vectors[y_valid[i]]-tflite_model_predictions[i])
    Distances[txt_1.format(Class1=y_valid[i])].append(dist)

#print(Distances)    
TH=[0]*NB_CLASSES  
for j in range(NB_CLASSES):
  Distances[txt_1.format(Class1=j)].sort()
  Dist=Distances[txt_1.format(Class1=j)]
  TH[j]=Dist[int(len(Dist)*0.90)]  



Threasholds=np.array(TH)
#print(Threasholds)
np.save('Threasholds_s.npy',Threasholds)


print("Done")




Data dimensions:
X: Training data's shape :  (41928, 475)
y: Training data's shape :  (41928,)
X: Validation data's shape :  (10782, 475)
y: Validation data's shape :  (10782,)
X: Testing data's shape :  (7188, 475)
y: Testing data's shape :  (7188,)
41928 train samples
10782 validation samples
7188 test samples
Shape:  (41928, 40)
Shape:  (10782, 40)
Done


In [16]:


def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(X_train_Rep).batch(1).take(100):
    # Model has only one input so each data point has one element.
    yield [input_value]
    
def Macro_F1(Matrix):
  Precisions=np.zeros(NB_CLASSES)
  Recalls=np.zeros(NB_CLASSES)
  
  epsilon=1e-8
  
  for k in range(len(Precisions)):
    Precisions[k]=Matrix[k][k]/np.sum(Matrix,axis=0)[k]
  #print(Precisions)
    
  Precision=np.average(Precisions)
  print("Precision:",Precision)
    
  for k in range(len(Recalls)):
    Recalls[k]=Matrix[k][k]/np.sum(Matrix,axis=1)[k]
   
  Recall=np.average(Recalls)
  print("Recall:",Recall)

  F1_Score=2*Precision*Recall/(Precision+Recall+epsilon)
  return F1_Score
    
def Micro_F1(matrix):
  epsilon=1e-8
  TP=0
  FP=0
  TN=0
  
  for k in range(NB_CLASSES):
    TP+=matrix[k][k]
    FP+=(np.sum(Matrix,axis=0)[k]-matrix[k][k])
    TN+=(np.sum(Matrix,axis=1)[k]-matrix[k][k])
    
  Micro_Prec=TP/(TP+FP)
  Micro_Rec=TP/(TP+TN)
  print("Micro Precision: ", Micro_Prec)
  print("Micro Recall: ", Micro_Rec)
  Micro_F1=2*Micro_Prec*Micro_Rec/(Micro_Rec+Micro_Prec+epsilon)
  
  return Micro_F1


def New_F1_Score(Matrix):
  Column_sum=np.sum(Matrix,axis=0)
  Raw_sum=np.sum(Matrix,axis=1)
  
  Precision_Differences=[]
  Recall_Differences=[]
  for i in range(NB_CLASSES):
    Precision_Differences.append(np.abs(2*Matrix[i][i]-Column_sum[i]))
    Recall_Differences.append(np.abs(2*Matrix[i][i]-Raw_sum[i]))
  
  Precision_Differences=np.array(Precision_Differences)
  Precision_Differences_Per=Precision_Differences/np.sum(Precision_Differences)
  Recall_Differences=np.array(Recall_Differences)
  Recall_Differences_Per=Recall_Differences/np.sum(Recall_Differences)
  
  #print('Precision_Differences_Per',Precision_Differences_Per)
  #print('Recall_Differences_Per',Recall_Differences_Per)
  
  Precisions=np.zeros(NB_CLASSES)
  Recalls=np.zeros(NB_CLASSES)
  
  epsilon=1e-8
  
  for k in range(len(Precisions)):
    Precisions[k]=(Matrix[k][k]/np.sum(Matrix,axis=0)[k])
  #print(Precisions)
  Precision=np.sum(np.array(Precisions)*Precision_Differences_Per)
  
  for k in range(len(Recalls)):
    Recalls[k]=(Matrix[k][k]/np.sum(Matrix,axis=1)[k])  #*Recall_Differences_Per[k]
  Recall=np.sum(np.array(Recalls)*Recall_Differences_Per)
  
  print('Precision: ',Precision)
  print('Recall: ',Recall)
    
  
  F1_Score=2*Precision*Recall/(Precision+Recall+epsilon)
  return F1_Score





X_open=np.load(dataset_dir+'X_open.npy')
X_open=X_open[:,:1500]
y_open = np.array([NB_CLASSES]*len(X_open))

X_test,y_test=shuffle(X_test, y_test)
#X_open,y_open=shuffle(X_open, y_open)

#X_open=X_open[:5000]
#y_open=y_open[:5000]


print("X_open shape:", X_open.shape)
#print(X_test[0])


# Convert data as float32 type
#X_train = X_train.astype('float32')
#X_valid = X_valid.astype('float32')
X_test = X_test.astype('float32')
X_open = X_open.astype('float32')
#y_train = y_train.astype('float32')
#y_valid = y_valid.astype('float32')
y_test = y_test.astype('int16')
#y_open = y_open.astype('int8')
# we need a [Length x 1] x n shape as input to the DF CNN (Tensorflow)
#X_train = X_train[:, :,np.newaxis]
#X_valid = X_valid[:, :,np.newaxis]


print()
#print(X_train[0])
#print(X_valid[0])
#print("################################")
#print(X_test[0])

#model=load_model('IoT_without_softmax_Robust_Addlayer_s10.hdf5')
Mean_Vectors=np.load('Mean_vectors.npy')
Threasholds=np.load('Threasholds_s.npy')




X_open = X_open[:, :,np.newaxis]


prediction_classes=[]
tflite_model_predictions=[]
for i in range(snapshot_number):
  model=load_model('snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions.append(model.predict(X_test))
  
tflite_model_predictions=np.array(tflite_model_predictions)
tflite_model_predictions=np.average(tflite_model_predictions,axis=0)

for i in range(len(tflite_model_predictions)):
  
    d=np.argmax(tflite_model_predictions[i], axis=0)
    if np.linalg.norm(tflite_model_predictions[i]-Mean_Vectors[d])>Threasholds[d]:
      prediction_classes.append(NB_CLASSES)
      
    else:
      prediction_classes.append(d)
      

    

prediction_classes_open=[]
tflite_model_predictions_open=[]
for i in range(snapshot_number):
  model=load_model('snapshot_'+str(i)+'.hdf5')
  tflite_model_predictions_open.append(model.predict(X_open))
  
tflite_model_predictions_open=np.array(tflite_model_predictions_open)
tflite_model_predictions_open=np.average(tflite_model_predictions_open,axis=0)

for i in range(len(tflite_model_predictions_open)):
    d=np.argmax(tflite_model_predictions_open[i], axis=0)
    if np.linalg.norm(tflite_model_predictions_open[i]-Mean_Vectors[d])>Threasholds[d]:
      prediction_classes_open.append(NB_CLASSES)
      
    else:
      prediction_classes_open.append(d)
      
    
    
acc_Close = accuracy_score(prediction_classes, y_test)
print('Test accuracy TFLITE model_Closed_set :', acc_Close)

acc_Open = accuracy_score(prediction_classes_open, y_open)
print('Test accuracy TFLITE model_Open_set :', acc_Open)


Matrix=[]
for i in range(NB_CLASSES+1):
  Matrix.append(np.zeros(NB_CLASSES+1))
  
  
for i in range(len(y_test)):
  Matrix[y_test[i]][prediction_classes[i]]+=1
  
for i in range(len(y_open)):
  Matrix[y_open[i]][prediction_classes_open[i]]+=1
  
#print(Matrix)




F1_Score=New_F1_Score(Matrix)


#print("Average Precision: ", Precision)
#print("Average Recall: ", Recall)
print("Average F1_Score: ", F1_Score)

print()
print("Micro")
print('Test accuracy TFLITE model_Closed_set :', acc_Close)
print('Test accuracy TFLITE model_Open_set :', acc_Open)
F1_Score=Micro_F1(Matrix)
print("Average F1_Score: ", F1_Score)

print()
print("Macro")
print('Test accuracy TFLITE model_Closed_set :', acc_Close)
print('Test accuracy TFLITE model_Open_set :', acc_Open)
F1_Score=Macro_F1(Matrix)
print("Average F1_Score: ", F1_Score)
print()


X_open shape: (86843, 475)

Test accuracy TFLITE model_Closed_set : 0.8505843071786311
Test accuracy TFLITE model_Open_set : 0.5403774627776562
Precision:  0.1031465866932639
Recall:  0.8591235326495368
Average F1_Score:  0.18418042343511215

Micro
Test accuracy TFLITE model_Closed_set : 0.8505843071786311
Test accuracy TFLITE model_Open_set : 0.5403774627776562
Micro Precision:  0.1322832601311149
Micro Recall:  0.8505843071786311
Average F1_Score:  0.22895874839606287

Macro
Test accuracy TFLITE model_Closed_set : 0.8505843071786311
Test accuracy TFLITE model_Open_set : 0.5403774627776562
Precision: 0.2382960484838764
Recall: 0.8495602728215361
Average F1_Score:  0.37219410346092785

